parameters:
#    pa_t_article.example.class: PaT\ArticleBundle\Example

services:
#    pa_t_article.example:
#        class: %pa_t_article.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
