pa_t_image:
    resource: "@PaTImageBundle/Resources/config/routing.yml"
    prefix:   /pictures

pa_t_article:
    resource: "@PaTArticleBundle/Resources/config/routing.yml"
    prefix:   /article

pa_t_voyage:
    resource: "@PaTVoyageBundle/Resources/config/routing.yml"
    prefix:   /voyage

pa_t_map:
    resource: "@PaTMapBundle/Resources/config/routing.yml"
    prefix:   /

pa_t_user:
    resource: "@PaTUserBundle/Resources/config/routing.yml"
    prefix:   /

pa_t_maquette:
    resource: "@PaTMaquetteBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

#HWIOAuthBundle routes
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login

facebook_login:
    pattern: /login/check-facebook

google_login:
    pattern: /login/check-google

cmf_media_file:
    resource: "@CmfMediaBundle/Resources/config/routing/file.xml"

cmf_media_image:
    resource: "@CmfMediaBundle/Resources/config/routing/image.xml"

_imagine:
    resource: .
    type:     imagine