parameters:
#    pa_t_maquette.example.class: PaT\MaquetteBundle\Example

services:
#    pa_t_maquette.example:
#        class: %pa_t_maquette.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
