<?php

namespace PaT\ImageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PicturesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PicturesRepository extends EntityRepository
{
}
