pa_t_voyage_homepage:
    pattern:  /index
    defaults: { _controller: PaTVoyageBundle:Voyage:index }

pa_t_voyage_add:
    pattern: /add
    defaults: { _controller: PaTVoyageBundle:Voyage:addtravel }

pa_t_voyage_delete:
    pattern: /delete/{id}
    defaults: { _controller: PaTVoyageBundle:Voyage:supprimer }
    requirements:
        id: \d+

pa_t_voyage_change:
    pattern: /change/{id}
    defaults: { _controller: PaTVoyageBundle:Voyage:change }
    requirements:
       id: \d+

pa_t_voyage_view:
    pattern: /view/{travelid}
    defaults: { _controller: PaTVoyageBundle:Voyage:view }
    requirements:
       travelid: \d+

pa_t_voyage_traveluser:
    pattern: /viewuser/{userid}
    defaults: { _controller: PaTVoyageBundle:Voyage:traveluser }
    requirements:
        userid: \d+