parameters:
#    pa_t_voyage.example.class: PaT\VoyageBundle\Example

services:
#    pa_t_voyage.example:
#        class: %pa_t_voyage.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
