<?php

namespace PaT\VoyageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BddImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BddImageRepository extends EntityRepository
{
}
