<?php

namespace PaT\VoyageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BddVoyageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BddVoyageRepository extends EntityRepository
{
}
