parameters:
#    pa_t_comm.example.class: PaT\CommBundle\Example

services:
#    pa_t_comm.example:
#        class: %pa_t_comm.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
