pa_t_image_add:
    pattern:  /add
    defaults: { _controller: PaTImageBundle:Add:index }

UploadPic:
    pattern:  /UploadPic
    defaults: { _controller: PaTImageBundle:Add:addPic }

ChoosePic:
    pattern:  /ChoosePic
    defaults: { _controller: PaTImageBundle:ChoosePicture:index }
