Account:
    path:  /myAccount
    defaults: { _controller: PaTUserBundle:Account:index }

Change_Status:
    path:  /myAccount/Change-Status
    defaults: { _controller: PaTUserBundle:ChangeStatus:index }

Change_Birthdate:
    path:  /myAccount/Change-Birthdate
    defaults: { _controller: PaTUserBundle:ChangeBirthdate:index }

Change_Country:
    path:  /myAccount/Change-Country
    defaults: { _controller: PaTUserBundle:ChangeCountry:index }

Change_VisitedCountry:
    path:  /myAccount/Change-Visited-Country
    defaults: { _controller: PaTUserBundle:ChangeVisitedCountries:index }

Oauth_Same_Email:
    path:  /oauth/same-email

Change_ProfilePicture:
    path:  /myAccount/Change-ProfilePicture
    defaults: { _controller:PaTUserBundle:ChangeProfilePicture:index }

changeProfilePic:
    path:  /myAccount/Change-ProfilePicture-Do-It
    defaults: { _controller:PaTUserBundle:ChangeProfilePicture:changePic }